name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  # Create draft release with matching tag. Ensure matches cargo version.
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version, from the tag
        if: env.VERSION == ''
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Show the version
        run: |
          echo "version is: $VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: true
          prerelease: false
    outputs:
      version: ${{ env.VERSION }}

  # Build and publish .deb file to release draft
  build-and-publish-deb:
    needs: ['create-release']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build .deb package
        run: cargo deb
      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: containeryard-deb
          path: ./target/debian/*.deb
      - name: Upload .deb to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./target/debian/containeryard-${{ needs.create-release.outputs.version }}-1_amd64.deb
          asset_name: containeryard-${{ needs.create-release.outputs.version }}-1_amd64.deb
          asset_content_type: application/x-debian-package
