name: Release

on:
  release:
    types: 
      - created
      - edited
      - published
      - unpublished
      - prereleased

jobs:
  build-and-publish-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build .deb package
        run: cargo deb
      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: containeryard-deb
          path: ./target/debian/*.deb
      - name: Upload .deb to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/debian/*.deb
          asset_name: containeryard_${{ github.ref_name }}.deb
          asset_content_type: application/x-debian-package
