name: Test Release Workflow

on:
  push:
    branches:
      - test-workflow

# Needed to create release
permissions:
  contents: write

jobs:
  build-and-publish-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
      - name: Update Rust to the latest version
        run: rustup update stable
      - name: Verify Rust version
        run: rustc --version

      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build .deb package
        run: cargo deb
      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: containeryard-deb
          path: ./target/debian/*.deb

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: test-tag-${{ github.sha }}
          release_name: Test Release ${{ github.sha }}
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .deb to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/debian/*.deb
          asset_name: containeryard_${{ github.sha }}.deb
          asset_content_type: application/x-debian-package

