name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable
    - name: Update Rust to the latest version
      run: rustup update stable
    - name: Verify Rust version
      run: rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
